apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cifs-credentials-template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    type: openshift.io/cifs
    stringData:
      password: "${PASSWORD}"
      username: "${USERNAME}"
parameters:
  - description: Name of the secret.
    displayName: Secret Name
    name: NAME
    value: cifs-credentials
    required: true
  - description: Username to access the CIFS share.
    displayName: Username
    name: USERNAME
    required: true
  - description: Password to access the CIFS share.
    displayName: Password
    name: PASSWORD
    required: true
