apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: An example .NET Core application.
    iconClass: icon-dotnet
    openshift.io/display-name: .NET Core Example
    tags: quickstart,dotnet,.net
    template.openshift.io/documentation-url: https://github.com/redhat-developer/s2i-dotnetcore
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/support-url: https://access.redhat.com
  creationTimestamp: 2018-12-19T04:47:53Z
  name: dotnet-example
  namespace: openshift
  resourceVersion: "1363"
  selfLink: /apis/template.openshift.io/v1/namespaces/openshift/templates/dotnet-example
  uid: 3eb65966-0349-11e9-9580-fa163e4067e5
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    type: openshift.io/cifs
    stringData:
      password: "${PASSWORD}"
      username: "${USERNAME}"
parameters:
  - description: Name of the secret.
    displayName: Secret Name
    name: NAME
    value: cifs-credentials
    required: true
  - description: Username to access the CIFS share.
    displayName: Username
    name: USERNAME
    required: true
  - description: Password to access the CIFS share.
    displayName: Password
    name: PASSWORD
    required: true
